# pip install requests
# pip install colorama
import requests
import json
import colorama
from colorama import Fore
from time import sleep
target = input("Enter target's User:")
urlinfo = 'https://www.instagram.com/{}/?__a=1'.format(target)
reqinfo = requests.get(urlinfo).json()
userid = str(reqinfo['logging_page_id'])
id = userid.split('_')[1]
print(Fore.LIGHTGREEN_EX + "target's id:" + id)
sleep(2)
print('==================')
print(Fore.BLUE + "he's username:" + target)
sleep(2)
print('==================')
bio = str(reqinfo['graphql']['user'].get('biography'))
link = str(reqinfo['graphql']['user'].get('external_url'))
followes = str(reqinfo['graphql']['user'].get('edge_followed_by').get('count'))
fullname = str(reqinfo['graphql']['user'].get('full_name'))
local = str(reqinfo['graphql']['user'].get('is_business_account'))
joined = str(reqinfo['graphql']['user'].get('is_joined_recently'))
print(Fore.LIGHTRED_EX + "target bio:" + bio)
sleep(2)
print('==================')
print(Fore.GREEN + 'target link:' + link)
sleep(2)
print('==================')
print(Fore.LIGHTBLUE_EX + 'Targget fullname:' + fullname)
sleep(2)
print('==================')
print(Fore.MAGENTA + 'Target followers:' + followes)
sleep(2)
print('==================')
print(Fore.BLUE + 'target business:' + local)
sleep(2)
print('==================')
print(Fore.CYAN + 'is target new:' + joined)
sleep(2)
print('==================')
private = str(reqinfo['graphql']['user'].get('is_private'))
print(Fore.LIGHTWHITE_EX + 'is private:' + private)
sleep(2)
print('==================')
pic = str(reqinfo['graphql']['user'].get('profile_pic_url'))
print(Fore.LIGHTMAGENTA_EX + 'link of  photo:' + pic)
sleep(2)
print('==================')
print('CODED BY' + ' ' + Fore.LIGHTMAGENTA_EX + 'S' + Fore.LIGHTWHITE_EX + 'T' + Fore.LIGHTGREEN_EX + 'R' + Fore.LIGHTYELLOW_EX + 'N' + Fore.LIGHTRED_EX + 'G')
